import type { RunPreset } from "./types";

export const RESULTS_DIR = process.env.S3_BENCH_OUTPUT_DIR ?? "./s3-bench-results";
export const THOROUGH_SCRIPT = "./scripts/bench-cli/engine.ts";

export const RUN_PRESETS: RunPreset[] = [
  {
    id: "normal",
    label: "Normal Use Benchmark",
    detail: "Balanced run for everyday operations, latency, consistency and throughput.",
    env: {
      S3_BENCH_REPEATS: "5",
      S3_BENCH_HEAVY_REPEATS: "2",
      S3_BENCH_SMALL_MB: "8",
      S3_BENCH_MEDIUM_MB: "64",
      S3_BENCH_LARGE_MB: "256",
      S3_BENCH_PARALLEL_UPLOADS: "16",
      S3_BENCH_PARALLEL_READS: "16",
      S3_BENCH_PARALLEL_DELETES: "32",
      S3_BENCH_BATCH_MIN_SUCCESS_RATE: "0.9",
      S3_BENCH_OP_TIMEOUT_MS: "120000",
      S3_BENCH_OP_RETRIES: "2",
      S3_BENCH_RETRY_BASE_DELAY_MS: "200",
    },
  },
  {
    id: "stress",
    label: "Insane Stress Benchmark",
    detail: "Heavier payloads and higher concurrency to pressure providers.",
    env: {
      S3_BENCH_REPEATS: "7",
      S3_BENCH_HEAVY_REPEATS: "4",
      S3_BENCH_SMALL_MB: "16",
      S3_BENCH_MEDIUM_MB: "128",
      S3_BENCH_LARGE_MB: "512",
      S3_BENCH_PARALLEL_UPLOADS: "32",
      S3_BENCH_PARALLEL_READS: "32",
      S3_BENCH_PARALLEL_DELETES: "64",
      S3_BENCH_MANY_OBJECTS_COUNT: "15000",
      S3_BENCH_LIST_TARGET: "12000",
      S3_BENCH_BATCH_MIN_SUCCESS_RATE: "0.85",
      S3_BENCH_OP_TIMEOUT_MS: "180000",
      S3_BENCH_OP_RETRIES: "3",
      S3_BENCH_RETRY_BASE_DELAY_MS: "250",
    },
  },
  {
    id: "resilience",
    label: "Resilience and Consistency",
    detail: "Focuses on repeated runs and transient failure recovery behavior.",
    env: {
      S3_BENCH_REPEATS: "10",
      S3_BENCH_HEAVY_REPEATS: "1",
      S3_BENCH_SMALL_MB: "4",
      S3_BENCH_MEDIUM_MB: "32",
      S3_BENCH_LARGE_MB: "128",
      S3_BENCH_PARALLEL_UPLOADS: "12",
      S3_BENCH_PARALLEL_READS: "12",
      S3_BENCH_PARALLEL_DELETES: "24",
      S3_BENCH_MISSING_KEY_REPEATS: "8",
      S3_BENCH_BATCH_MIN_SUCCESS_RATE: "0.95",
      S3_BENCH_OP_TIMEOUT_MS: "120000",
      S3_BENCH_OP_RETRIES: "4",
      S3_BENCH_RETRY_BASE_DELAY_MS: "300",
    },
  },
  {
    id: "study",
    label: "Blog Post and Deep Study",
    detail: "Ultra-comprehensive run tuned for deep analysis, anomalies, and publishable comparisons.",
    env: {
      S3_BENCH_REPEATS: "12",
      S3_BENCH_HEAVY_REPEATS: "6",
      S3_BENCH_SMALL_MB: "8",
      S3_BENCH_MEDIUM_MB: "128",
      S3_BENCH_LARGE_MB: "512",
      S3_BENCH_PARALLEL_UPLOADS: "40",
      S3_BENCH_PARALLEL_READS: "40",
      S3_BENCH_PARALLEL_DELETES: "80",
      S3_BENCH_MANY_OBJECTS_COUNT: "25000",
      S3_BENCH_MANY_OBJECTS_SIZE_BYTES: "2048",
      S3_BENCH_LIST_TARGET: "20000",
      S3_BENCH_MISSING_KEY_REPEATS: "10",
      S3_BENCH_BATCH_MIN_SUCCESS_RATE: "0.82",
      S3_BENCH_OP_TIMEOUT_MS: "240000",
      S3_BENCH_OP_RETRIES: "4",
      S3_BENCH_RETRY_BASE_DELAY_MS: "350",
    },
  },
];
