import { browseRecentRunsFlow, runPresetFlow, showRankingFlow, showStudyReportFlow } from "./actions";
import { closePrompts, choose } from "./prompts";
import { banner, drawMenu, printErr, printKeyHint } from "./ui";
import type { MenuChoice } from "./types";

const MAIN_CHOICES: MenuChoice[] = [
  {
    id: "run",
    label: "Run Benchmarks",
    detail: "Launch very-fast, normal, stress, resilience, or study benchmark profiles.",
  },
  {
    id: "recent",
    label: "Browse Recent Runs",
    detail: "View latest run sessions and drill into run-level rankings.",
  },
  {
    id: "ranking",
    label: "Open Ranking Table",
    detail: "Pick a run and inspect full category scoring side by side.",
  },
  {
    id: "study",
    label: "Open Study Report",
    detail: "Open the deep-dive anomaly and story report generated by study runs.",
  },
  {
    id: "quit",
    label: "Quit",
    detail: "Exit benchmark control.",
  },
];

async function mainMenu(): Promise<void> {
  let done = false;

  while (!done) {
    banner("Keyboard Control", "Enter-driven benchmark control center");
    drawMenu("Main Menu", MAIN_CHOICES);
    printKeyHint();
    const picked = await choose(MAIN_CHOICES);

    if (picked === "quit") {
      done = true;
      continue;
    }

    if (picked === "back") {
      continue;
    }

    if (picked.id === "run") {
      await runPresetFlow();
      continue;
    }

    if (picked.id === "recent") {
      await browseRecentRunsFlow();
      continue;
    }

    if (picked.id === "ranking") {
      await showRankingFlow();
      continue;
    }

    if (picked.id === "study") {
      await showStudyReportFlow();
      continue;
    }

    if (picked.id === "quit") {
      done = true;
    }
  }
}

void mainMenu()
  .catch((error) => {
    const msg = error instanceof Error ? error.stack ?? error.message : String(error);
    printErr(msg);
    process.exitCode = 1;
  })
  .finally(() => {
    closePrompts();
  });
