import { useEffect, useMemo, useRef, useState } from "react";
import { AppShell } from "../components/AppShell";
import { PhIcon } from "../components/ui/PhIcon";
import type { AppBootstrap, FrontendUser } from "../shared/types/app";
import { formatBytes } from "../shared/utils/format";

type HackatimeProject = {
	id: string;
	name: string;
	hours: number;
};

type BonusTier = {
	hours: number;
	percent: number;
	enabled: boolean;
};

type FormErrors = Record<string, string | string[] | undefined>;

function firstError(value: string | string[] | undefined): string | null {
	if (!value) return null;
	if (Array.isArray(value)) return value[0] || null;
	return value;
}

export function YswsSubmitPage({ bootstrap }: { bootstrap: AppBootstrap }) {
	const p = bootstrap.props as {
		user?: FrontendUser | null;
		hackatimeProjects?: HackatimeProject[];
		quotaPerHour?: number;
		yswsBonusTiers?: BonusTier[];
		quotaPerHourFormatted?: string;
		errors?: FormErrors;
		values?: Record<string, unknown>;
		error?: string;
	};

	const values = p.values || {};
	const quotaPerHour = p.quotaPerHour || 0;
	const tiers = p.yswsBonusTiers || [];

	const initialSelected = String(values.hackatimeProject || "")
		.split(",")
		.filter(Boolean);

	const [selectedIds, setSelectedIds] = useState<string[]>(initialSelected);
	const [search, setSearch] = useState("");
	const [selectorOpen, setSelectorOpen] = useState(false);
	const selectorRef = useRef<HTMLDivElement | null>(null);

	const [aiLevel, setAiLevel] = useState<number>(() => {
		const tool = String(values.aiToolUsage || "none");
		if (tool === "tab-completion") return 1;
		if (tool === "inline") return 2;
		if (tool === "chat" || tool === "command-k") return 3;
		if (tool === "no-code") return 4;
		return 0;
	});
	const [aiPercent, setAiPercent] = useState<number>(
		Number(values.aiPercent || 0),
	);

	const [preview, setPreview] = useState<string>("");
	const [dragActive, setDragActive] = useState(false);
	const fileInputRef = useRef<HTMLInputElement | null>(null);

	useEffect(() => {
		const onMouseDown = (event: MouseEvent) => {
			if (
				selectorOpen &&
				selectorRef.current &&
				!selectorRef.current.contains(event.target as Node)
			) {
				setSelectorOpen(false);
			}
		};
		document.addEventListener("mousedown", onMouseDown);
		return () => document.removeEventListener("mousedown", onMouseDown);
	}, [selectorOpen]);

	const projects = p.hackatimeProjects || [];

	const filteredProjects = useMemo(() => {
		if (!search.trim()) return projects;
		return projects.filter((item) =>
			item.name.toLowerCase().includes(search.toLowerCase()),
		);
	}, [projects, search]);

	const baseRewardBytes = useMemo(() => {
		const selected = projects.filter((project) =>
			selectedIds.includes(project.id),
		);
		const hours = selected.reduce((acc, item) => acc + item.hours, 0);
		return hours * quotaPerHour;
	}, [projects, quotaPerHour, selectedIds]);

	const activeTierBonus = useMemo(() => {
		const totalHours = projects
			.filter((project) => selectedIds.includes(project.id))
			.reduce((acc, item) => acc + item.hours, 0);
		const valid = tiers
			.filter((tier) => tier.enabled && totalHours >= tier.hours)
			.sort((a, b) => b.hours - a.hours);
		return valid[0]?.percent || 0;
	}, [projects, selectedIds, tiers]);

	const totalRewardBytes = Math.floor(
		baseRewardBytes * (1 + activeTierBonus / 100),
	);

	const selectedLabel =
		selectedIds.length === 0
			? "Select Project(s)..."
			: `${selectedIds.length} Project${selectedIds.length > 1 ? "s" : ""} Selected`;

	const requiresDetails = aiLevel > 0 && aiLevel < 4;
	const isRejected = aiLevel === 4 || (requiresDetails && aiPercent > 30);

	const aiToolUsage =
		aiLevel === 0
			? "none"
			: aiLevel === 1
				? "tab-completion"
				: aiLevel === 2
					? "inline"
					: aiLevel === 3
						? "chat"
						: "no-code";

	const aiLabel =
		aiLevel === 0
			? "No AI Used"
			: aiLevel === 1
				? "Tab Completion"
				: aiLevel === 2
					? "Inline Generation"
					: aiLevel === 3
						? "Chat Assistant"
						: "Purely AI / No Code";

	const aiDescription =
		aiLevel === 0
			? "100% human written code."
			: aiLevel === 1
				? "Used Copilot/Ghostwriter for line completions."
				: aiLevel === 2
					? "Used Ctrl+I / Cmd+K to generate small blocks."
					: aiLevel === 3
						? "Used ChatGPT/Claude to write functions or debug."
						: "Entirely generated by AI tools (v0, bolt, etc).";

	const setFilePreview = (file?: File | null) => {
		if (!file || !file.type.startsWith("image/")) {
			setPreview("");
			return;
		}
		setPreview(URL.createObjectURL(file));
	};

	return (
		<AppShell
			title={bootstrap.title}
			user={p.user || null}
			config={bootstrap.config}
		>
			<div className="max-w-3xl mx-auto py-12">
				<div className="mb-8 text-center">
					<h1 className="text-4xl font-extrabold tracking-tight mb-2 text-white">
						YSWS
					</h1>
					<p className="text-xl text-white/60">
						Ship your projects, earn more storage. Simple as that.
					</p>
					<p className="mt-4 text-sm text-hc-green bg-hc-green/10 border border-hc-green/20 rounded-full px-4 py-1 inline-block">
						Earn {p.quotaPerHourFormatted || formatBytes(quotaPerHour)} per hour
						tracked on Hackatime
					</p>
				</div>

				<div className="flex justify-center mb-8">
					<a
						href="/ysws"
						className="text-sm text-text-muted hover:text-white transition-colors flex items-center gap-2"
					>
						<PhIcon className="ph ph-arrow-left text-lg" />
						Back to Dashboard
					</a>
				</div>

				<div className="bg-hc-dark border border-white/10 rounded-3xl p-8 card-shadow">
					<form
						action="/ysws/submit"
						method="POST"
						encType="multipart/form-data"
						className="space-y-6"
					>
						<div className="space-y-4">
							<h3 className="text-lg font-bold border-b border-white/10 pb-2 mb-4">
								Project Details
							</h3>

							<div className="grid grid-cols-1 md:grid-cols-2 gap-4">
								<div>
									<label
										htmlFor="project-name"
										className="block text-sm font-bold text-text-muted uppercase tracking-wider mb-2"
									>
										Project Name
									</label>
									<input
										id="project-name"
										type="text"
										name="projectName"
										defaultValue={String(values.projectName || "")}
										required
										className="w-full bg-black/30 border border-white/10 rounded-xl px-4 py-3 text-white focus:border-hc-red focus:outline-none focus:ring-1 focus:ring-hc-red transition-colors placeholder-white/20"
										placeholder="My Awesome Project"
									/>
									{firstError(p.errors?.projectName) ? (
										<p className="text-red-400 text-xs mt-1">
											{firstError(p.errors?.projectName)}
										</p>
									) : null}
								</div>

								<div>
									<label
										htmlFor="short-description"
										className="block text-sm font-bold text-text-muted uppercase tracking-wider mb-2"
									>
										Short Description
									</label>
									<input
										id="short-description"
										type="text"
										name="shortDescription"
										defaultValue={String(values.shortDescription || "")}
										required
										className="w-full bg-black/30 border border-white/10 rounded-xl px-4 py-3 text-white focus:border-hc-red focus:outline-none focus:ring-1 focus:ring-hc-red transition-colors placeholder-white/20"
										placeholder="A website that does X..."
									/>
									{firstError(p.errors?.shortDescription) ? (
										<p className="text-red-400 text-xs mt-1">
											{firstError(p.errors?.shortDescription)}
										</p>
									) : null}
								</div>
							</div>

							<div className="grid grid-cols-1 md:grid-cols-2 gap-4">
								<div>
									<label
										htmlFor="repo-url"
										className="block text-sm font-bold text-text-muted uppercase tracking-wider mb-2"
									>
										Code URL (Repo)
									</label>
									<input
										id="repo-url"
										type="url"
										name="repoUrl"
										defaultValue={String(values.repoUrl || "")}
										required
										className="w-full bg-black/30 border border-white/10 rounded-xl px-4 py-3 text-white focus:border-hc-red focus:outline-none focus:ring-1 focus:ring-hc-red transition-colors placeholder-white/20 font-mono text-sm"
										placeholder="https://github.com/..."
									/>
									{firstError(p.errors?.repoUrl) ? (
										<p className="text-red-400 text-xs mt-1">
											{firstError(p.errors?.repoUrl)}
										</p>
									) : null}
								</div>

								<div>
									<label
										htmlFor="demo-url"
										className="block text-sm font-bold text-text-muted uppercase tracking-wider mb-2"
									>
										Demo / Playable URL
									</label>
									<input
										id="demo-url"
										type="url"
										name="demoUrl"
										defaultValue={String(values.demoUrl || "")}
										required
										className="w-full bg-black/30 border border-white/10 rounded-xl px-4 py-3 text-white focus:border-hc-red focus:outline-none focus:ring-1 focus:ring-hc-red transition-colors placeholder-white/20 font-mono text-sm"
										placeholder="https://my-project.hackclub.app"
									/>
									{firstError(p.errors?.demoUrl) ? (
										<p className="text-red-400 text-xs mt-1">
											{firstError(p.errors?.demoUrl)}
										</p>
									) : null}
								</div>
							</div>

							<div>
								<label
									htmlFor="file-input"
									className="block text-sm font-medium text-text-muted mb-2"
								>
									Project Screenshot
								</label>

								<label
									htmlFor="file-input"
									className={`border-2 border-dashed rounded-xl p-8 transition-colors group relative ${dragActive ? "border-white/40 bg-white/5" : "border-white/20 hover:border-white/40"}`}
									onDragEnter={(e) => {
										e.preventDefault();
										setDragActive(true);
									}}
									onDragOver={(e) => {
										e.preventDefault();
										setDragActive(true);
									}}
									onDragLeave={(e) => {
										e.preventDefault();
										setDragActive(false);
									}}
									onDrop={(e) => {
										e.preventDefault();
										setDragActive(false);
										const file = e.dataTransfer.files?.[0];
										setFilePreview(file);
										if (file && fileInputRef.current) {
											const dt = new DataTransfer();
											dt.items.add(file);
											fileInputRef.current.files = dt.files;
										}
									}}
								>
									<input
										ref={fileInputRef}
										id="file-input"
										type="file"
										name="screenshotFile"
										accept="image/*"
										className="absolute inset-0 w-full h-full opacity-0 cursor-pointer z-10"
										onChange={(e) =>
											setFilePreview(e.target.files?.[0] || null)
										}
									/>

									{preview ? (
										<div className="flex items-center justify-center gap-4">
											<img
												src={preview}
												alt="Preview"
												className="max-h-48 rounded-lg shadow-lg"
											/>
											<button
												type="button"
												onClick={(e) => {
													e.preventDefault();
													setPreview("");
													if (fileInputRef.current)
														fileInputRef.current.value = "";
												}}
												className="bg-red-500/20 hover:bg-red-500/40 text-red-400 p-2 rounded-lg transition-colors z-20"
											>
												<PhIcon className="ph ph-x text-lg" />
											</button>
										</div>
									) : (
										<div className="text-center">
											<div className="w-12 h-12 rounded-full bg-white/5 flex items-center justify-center mx-auto mb-3 group-hover:bg-white/10 transition-colors">
												<PhIcon className="ph ph-image text-2xl text-text-muted group-hover:text-white transition-colors" />
											</div>
											<p className="text-sm font-medium text-white">
												Drop your screenshot here, or{" "}
												<span className="text-hc-red">browse</span>
											</p>
											<p className="text-xs text-text-muted mt-1">
												Supports PNG, JPG, WEBP
											</p>
										</div>
									)}
								</label>

								<div className="mt-4 flex items-center gap-3">
									<div className="h-px bg-white/10 flex-1" />
									<span className="text-xs text-text-muted uppercase font-bold tracking-wider">
										OR
									</span>
									<div className="h-px bg-white/10 flex-1" />
								</div>

								<div className="mt-4">
									<label
										htmlFor="screenshot-url"
										className="block text-xs font-medium text-text-muted mb-1 uppercase tracking-wider"
									>
										Provide URL
									</label>
									<input
										id="screenshot-url"
										type="url"
										name="screenshotUrl"
										defaultValue={String(values.screenshotUrl || "")}
										className="w-full bg-black/20 border border-white/10 rounded px-3 py-2 text-white focus:border-hc-red focus:outline-none transition-colors text-sm font-mono"
										placeholder="https://..."
									/>
								</div>
								{firstError(p.errors?.screenshotUrl) ? (
									<p className="text-red-400 text-xs mt-1">
										{firstError(p.errors?.screenshotUrl)}
									</p>
								) : null}
							</div>
						</div>

						<div
							className="space-y-4 pt-4 border-t border-white/10"
							ref={selectorRef}
						>
							<h3 className="text-lg font-bold text-white mb-2">
								Hackatime Integration
							</h3>
							<p className="block text-sm font-bold text-text-muted uppercase tracking-wider mb-2">
								Select Hackatime Project(s)
							</p>
							<input
								type="hidden"
								name="hackatimeProject"
								value={selectedIds.join(",")}
								required
							/>

							<button
								type="button"
								onClick={() => setSelectorOpen((v) => !v)}
								className="w-full bg-black/30 border border-white/10 rounded-xl px-4 py-3 text-left text-white focus:outline-none focus:ring-1 focus:ring-hc-red transition-colors flex justify-between items-center group hover:bg-black/40"
							>
								<span
									className={
										selectedIds.length === 0 ? "text-text-muted" : "text-white"
									}
								>
									{selectedLabel}
								</span>
								<PhIcon className="ph ph-caret-down text-xl text-text-muted group-hover:text-white transition-colors" />
							</button>

							{selectorOpen ? (
								<div className="relative">
									<div className="absolute z-50 w-full mt-2 bg-hc-dark border border-white/10 rounded-xl shadow-xl max-h-60 overflow-hidden flex flex-col">
										<div className="p-2 border-b border-white/10 bg-black/20">
											<input
												type="text"
												value={search}
												onChange={(e) => setSearch(e.target.value)}
												placeholder="Search projects..."
												className="w-full bg-black/30 border border-white/10 rounded-lg px-3 py-2 text-sm text-white focus:outline-none focus:border-hc-blue placeholder-white/20"
											/>
										</div>
										<div className="overflow-y-auto flex-1 p-1 scrollbar-thin">
											{filteredProjects.map((project) => {
												const selected = selectedIds.includes(project.id);
												return (
													<button
														key={project.id}
														type="button"
														onClick={() =>
															setSelectedIds((prev) =>
																selected
																	? prev.filter((id) => id !== project.id)
																	: [...prev, project.id],
															)
														}
														className="w-full text-left px-3 py-2 rounded-lg hover:bg-white/5 transition-colors flex justify-between items-center group"
													>
														<div className="flex items-center gap-3">
															<div
																className={`w-4 h-4 rounded border flex items-center justify-center transition-colors ${selected ? "bg-hc-red border-hc-red" : "border-white/30"}`}
															>
																{selected ? (
																	<PhIcon className="ph ph-check text-xs text-white" />
																) : null}
															</div>
															<div>
																<div className="font-bold text-sm text-white">
																	{project.name}
																</div>
																<div className="text-xs text-text-muted group-hover:text-white/70">
																	{project.hours} hours tracked
																</div>
															</div>
														</div>
														<div className="text-xs font-mono text-hc-green bg-hc-green/10 px-2 py-0.5 rounded">
															{formatBytes(project.hours * quotaPerHour)}
														</div>
													</button>
												);
											})}
											{filteredProjects.length === 0 ? (
												<div className="px-4 py-3 text-sm text-text-muted text-center italic">
													No projects found
												</div>
											) : null}
										</div>
									</div>
								</div>
							) : null}

							<div
								className="mt-2 p-3 rounded-lg bg-black/20 border border-white/5 flex flex-col gap-2"
								style={{ display: selectedIds.length > 0 ? "flex" : "none" }}
							>
								<div className="flex justify-between items-center">
									<span className="text-sm text-text-muted">Base Reward:</span>
									<span className="text-sm font-bold text-white">
										{formatBytes(baseRewardBytes)}
									</span>
								</div>
								<div
									className="flex justify-between items-center"
									style={{ display: activeTierBonus > 0 ? "flex" : "none" }}
								>
									<span className="text-sm text-text-muted">Tier Bonus:</span>
									<span className="text-sm font-bold text-hc-green">
										+{activeTierBonus}%
									</span>
								</div>
								<div className="flex justify-between items-center pt-2 border-t border-white/5">
									<span className="text-sm font-bold text-white">
										Total Reward:
									</span>
									<span className="text-sm font-bold text-hc-green">
										{formatBytes(totalRewardBytes)}
									</span>
								</div>
							</div>

							{firstError(p.errors?.hackatimeProject) ? (
								<p className="text-red-400 text-xs mt-1">
									{firstError(p.errors?.hackatimeProject)}
								</p>
							) : null}
						</div>

						<div className="space-y-4 pt-4 border-t border-white/10">
							<h3 className="text-lg font-bold text-white mb-2">
								AI Usage Declaration
							</h3>
							<input type="hidden" name="aiToolUsage" value={aiToolUsage} />
							<input
								type="hidden"
								name="usedAi"
								value={aiLevel > 0 ? "yes" : "no"}
							/>

							<div className="bg-black/30 rounded-xl p-6 border border-white/10">
								<div className="mb-6">
									<label
										htmlFor="ai-level"
										className="block text-sm font-bold text-text-muted uppercase tracking-wider mb-1"
									>
										How much AI did you use?
									</label>
									<p className="text-xs text-text-muted/60 mb-1">
										Using AI to ask questions or explain concepts does not count
										as AI usage, only AI-generated code does.
									</p>
									<p className="text-xs text-red-400 font-bold">
										Honesty does not hurt your payout, but lying will get your
										project rejected.
									</p>
								</div>

								<input
									id="ai-level"
									type="range"
									min={0}
									max={4}
									step={1}
									value={aiLevel}
									onChange={(e) => setAiLevel(Number(e.target.value))}
									className="w-full accent-hc-red cursor-pointer"
								/>
								<div className="flex justify-between text-[10px] text-text-muted mt-2 font-mono uppercase tracking-wider">
									<span>None</span>
									<span>Tab</span>
									<span>Inline</span>
									<span>Chat</span>
									<span>No Code</span>
								</div>

								<div
									className={`text-center p-4 rounded-lg border mt-5 ${isRejected ? "border-red-500/50 bg-red-500/10" : aiLevel === 0 ? "border-hc-green/30 bg-hc-green/10" : "border-white/10 bg-white/5"}`}
								>
									<h4 className="font-bold text-lg text-white">{aiLabel}</h4>
									<p className="text-sm text-text-muted">{aiDescription}</p>
									{aiLevel === 4 ? (
										<p className="text-red-400 text-sm mt-2 font-bold">
											Purely AI-generated / No Code projects are not eligible
											for rewards.
										</p>
									) : null}
									{requiresDetails && aiPercent > 30 ? (
										<p className="text-red-400 text-sm mt-2 font-bold">
											Projects with &gt;30% AI generation are not eligible for
											rewards.
										</p>
									) : null}
								</div>

								{requiresDetails ? (
									<div className="mt-6 space-y-4">
										<div>
											<div className="flex justify-between items-center mb-2">
												<label
													htmlFor="ai-percent"
													className="block text-sm font-bold text-text-muted uppercase tracking-wider"
												>
													Percentage of AI Generated Code
												</label>
												<span className="text-sm font-mono text-hc-red">
													{aiPercent}%
												</span>
											</div>
											<input
												id="ai-percent"
												type="range"
												name="aiPercent"
												value={aiPercent}
												min={0}
												max={100}
												onChange={(e) => setAiPercent(Number(e.target.value))}
												className="w-full accent-hc-red cursor-pointer"
											/>
											<div className="flex justify-between text-xs text-text-muted mt-2 font-mono">
												<span>0%</span>
												<span>100%</span>
											</div>
											{aiPercent > 30 ? (
												<p className="text-xs text-red-400 mt-2 font-bold">
													Projects with &gt;30% AI generation are not eligible
													for rewards.
												</p>
											) : null}
										</div>

										<div>
											<label
												htmlFor="ai-usage-description"
												className="block text-sm font-bold text-text-muted uppercase tracking-wider mb-2"
											>
												Description of AI Usage (Required)
											</label>
											<textarea
												id="ai-usage-description"
												name="aiUsageDescription"
												rows={3}
												defaultValue={String(values.aiUsageDescription || "")}
												required
												className="w-full bg-black/30 border border-white/10 rounded-xl px-4 py-3 text-white focus:border-hc-red focus:outline-none focus:ring-1 focus:ring-hc-red transition-colors placeholder-white/20"
												placeholder="I used Copilot for boilerplate and some regex..."
											/>
										</div>
									</div>
								) : null}

								{p.error ? (
									<p className="text-red-400 text-xs mt-1">{p.error}</p>
								) : null}
							</div>
						</div>

						<div className="space-y-4 pt-6 border-t border-white/10">
							<label className="flex items-start gap-4 cursor-pointer p-5 bg-black/30 rounded-xl border border-white/10 hover:border-white/20 transition-colors group">
								<input
									type="checkbox"
									name="readmeConfirmed"
									required
									defaultChecked={Boolean(values.readmeConfirmed)}
									className="mt-1 w-5 h-5 rounded border-white/30 text-hc-red focus:ring-hc-red focus:ring-offset-0 bg-transparent"
								/>
								<div>
									<div className="font-bold text-white text-base">
										I confirm my project has a great README
									</div>
									<div className="text-sm text-text-muted mt-1">
										Submissions without a descriptive README explaining what the
										project is and how to run it will be rejected.
									</div>
								</div>
							</label>
							{firstError(p.errors?.readmeConfirmed) ? (
								<p className="text-red-400 text-xs mt-1">
									{firstError(p.errors?.readmeConfirmed)}
								</p>
							) : null}
						</div>

						<button
							type="submit"
							className="w-full bg-hc-red hover:bg-red-600 text-white font-bold py-4 rounded-xl transition-all hover:scale-[1.02] shadow-lg shadow-hc-red/20 text-lg"
						>
							Ship Project
						</button>
					</form>
				</div>
			</div>
		</AppShell>
	);
}
