import { expect, test } from "bun:test";
import { eq } from "drizzle-orm";
import { db } from "../src/db";
import { bucketKeys, buckets, users } from "../src/db/schema";
import { authenticate } from "../src/middleware/auth";
import { handleS3Request } from "../src/features/s3-api";
import { AwsClient } from "aws4fetch";

const USER_A_ID = "sec-user-a";
const BUCKET_A_NAME = "sec-bucket-a";
const KEY_A_ACCESS = "SECKEYAACCESS";
const KEY_A_SECRET = "SECKEYASECRET";

const USER_B_ID = "sec-user-b";
const BUCKET_B_NAME = "sec-bucket-b";
const KEY_B_ACCESS = "SECKEYBACCESS";
const KEY_B_SECRET = "SECKEYBSECRET";

async function setup() {
    // Cleanup
    await db.delete(bucketKeys).where(eq(bucketKeys.accessKey, KEY_A_ACCESS));
    await db.delete(bucketKeys).where(eq(bucketKeys.accessKey, KEY_B_ACCESS));
    await db.delete(buckets).where(eq(buckets.name, BUCKET_A_NAME));
    await db.delete(buckets).where(eq(buckets.name, BUCKET_B_NAME));
    await db.delete(users).where(eq(users.id, USER_A_ID));
    await db.delete(users).where(eq(users.id, USER_B_ID));

    // User A
    await db.insert(users).values({ id: USER_A_ID, email: "a@sec.test" });
    const [bucketA] = await db.insert(buckets).values({ name: BUCKET_A_NAME, userId: USER_A_ID, isPublic: false }).returning();
    await db.insert(bucketKeys).values({ bucketId: bucketA.id, accessKey: KEY_A_ACCESS, secretKey: KEY_A_SECRET });

    // User B
    await db.insert(users).values({ id: USER_B_ID, email: "b@sec.test" });
    const [bucketB] = await db.insert(buckets).values({ name: BUCKET_B_NAME, userId: USER_B_ID, isPublic: false }).returning();
    await db.insert(bucketKeys).values({ bucketId: bucketB.id, accessKey: KEY_B_ACCESS, secretKey: KEY_B_SECRET });

    return { bucketA, bucketB };
}

async function teardown() {
    await db.delete(bucketKeys).where(eq(bucketKeys.accessKey, KEY_A_ACCESS));
    await db.delete(bucketKeys).where(eq(bucketKeys.accessKey, KEY_B_ACCESS));
    await db.delete(buckets).where(eq(buckets.name, BUCKET_A_NAME));
    await db.delete(buckets).where(eq(buckets.name, BUCKET_B_NAME));
    await db.delete(users).where(eq(users.id, USER_A_ID));
    await db.delete(users).where(eq(users.id, USER_B_ID));
}

test("Security: Cross-Bucket Access (Auth Mismatch)", async () => {
    await setup();

    // Client A tries to access Bucket B
    const clientA = new AwsClient({
        accessKeyId: KEY_A_ACCESS,
        secretAccessKey: KEY_A_SECRET,
        service: "s3",
    });

    // Construct a request to Bucket B
    // We need to manually construct the request to pass to authenticate
    // AwsClient.fetch signs the request.
    
    const url = `https://cargo.deployor.dev/${BUCKET_B_NAME}/secret.txt`;
    const signed = await clientA.sign(url, { method: "PUT" });
    
    // We need to convert the signed request (which might be a Request object or headers) to something we can pass to authenticate
    // AwsClient.sign returns a Request object if using fetch-like signature, or headers.
    // Actually AwsClient.fetch does the signing.
    // But we want to test `authenticate` logic without actually sending network request (or we can mock).
    // But `authenticate` takes a `Request`.
    
    // Let's use `clientA.fetch` but intercept it? No, we are running in bun test.
    // We can just use the headers generated by clientA.
    
    const req = new Request(url, {
        method: "PUT",
        headers: signed.headers
    });

    // Now pass to authenticate
    const authResult = await authenticate(req);

    // Expectation: 
    // If we enforce bucket matching, this should fail (return Response 403).
    // If we don't, it returns User A and Bucket A (because Key A maps to Bucket A).
    
    // If it returns a Response, check status
    if (authResult instanceof Response) {
        expect(authResult.status).toBe(403);
    } else {
        // If it returns a user/bucket, check which one.
        // If it returns Bucket A, it means it ignored the URL bucket and used the Key's bucket.
        // This is the "confusing behavior" mentioned.
        // The user wants "security checks".
        // Accessing Bucket B URL with Key A should probably be denied to prevent confusion/mistakes.
        console.log("Auth Result Bucket:", authResult.bucket.name);
        expect(authResult.bucket.name).toBe(BUCKET_B_NAME); // It SHOULD match the URL bucket if we are strict
    }

    await teardown();
});

test("Security: Public Bucket Access", async () => {
    const { bucketB } = await setup();
    
    // Make Bucket B public
    await db.update(buckets).set({ isPublic: true }).where(eq(buckets.id, bucketB.id));

    const req = new Request(`https://cargo.deployor.dev/${BUCKET_B_NAME}/public.txt`, {
        method: "GET"
    });

    const authResult = await authenticate(req);
    
    expect(authResult).not.toBeInstanceOf(Response);
    if (!(authResult instanceof Response)) {
        expect(authResult.mode).toBe("public");
        expect(authResult.bucket.name).toBe(BUCKET_B_NAME);
    }

    await teardown();
});

test("Security: Private Bucket Access (Anonymous)", async () => {
    await setup();

    const req = new Request(`https://cargo.deployor.dev/${BUCKET_A_NAME}/private.txt`, {
        method: "GET"
    });

    const authResult = await authenticate(req);
    
    expect(authResult).toBeInstanceOf(Response);
    if (authResult instanceof Response) {
        expect(authResult.status).toBe(403);
    }

    await teardown();
});
